# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      PACKAGE_NAME: UtilityMe
      
    runs-on: macos-latest

    steps:
    - name: Repository checkout
      uses: actions/checkout@v3
    
    - name: Lint
      run: swiftlint

    - name: Build for macOS
      run: swift build -v --package-path UtilityMe/
      
    - name: Run macOS tests
      run: swift test -v --package-path UtilityMe/
